### ISSUE TITLE
Como retornar os dados em json?

### ISSUE THREAD

**Issue by mvfsillva** [banco-br/nodejs-cnab#12]
Estava acompanhando o desenvolvimento da lib e notei que na verdade ela gera um arquivo `.rem`, porén, no inicio estava como `.json`, vocês pretendem gerar também o `json` ou apenas o `rem`?

**Comment by mariohmol** [comment]
A ideia aqui é fazer o vai e volta... tipo.. 

vai: o JSON vem do seu banco e oc cria o arquivo remessa (rem).. 
vem: recebe o arquivo retorno e gera de volta o json

se puder ajudar no dev... tem muita coisa q da pra ajudar.. 
fazer os arquivos de exemplo pros testes mesmo é facin

https://github.com/banco-br/nodejs-cnab/issues/3

**Comment by mvfsillva** [comment]
Opa, com certeza posso ajudar!

**Comment by mariohmol** [comment]
boa!

adicionei no readme exemplo de como faz pra ler do retorno pro objeto
