### ISSUE TITLE
Utilizar o alexjoverm/typescript-library-starter

### ISSUE THREAD

**Issue by ymoreiratiti** [banco-br/nodejs-cnab#18]
https://github.com/alexjoverm/typescript-library-starter

Vantagens de utilizar este Starter Kit

- Eslint bem restrito (Força a padronização e facilita a comparação pelo git diff)
- Jest Tests (Podemos utilizar os snaptshots para comparar o arquivo gerado. Acredito que facilitaria bastante...
- Documentação gerada automaticamente (Pelo minimo da API)
- Travis/Coverall
- Tambem podemos configurar o semantic-release. Ao mesclar o pull request no master, automaticamente versiona e libera no NPM
- Changelog automatizado baseado no texto do commit

**Comment by ymoreiratiti** [comment]
@mariohmol O que voce acha?

**Comment by mariohmol** [comment]
fino demais!

**Comment by mariohmol** [comment]
boa!
