### ISSUE TITLE
Manuteção

### ISSUE THREAD

**Issue by GTEDESCO** [banco-br/nodejs-cnab#7]
Olá, ainda trabalhando neste projeto?
Gostaria de contribuir.
E uma duvida para layouts 240 precisaria de alguma alteração?
Teria algum exemplo de uso ?

Abs

**Comment by mariohmol** [comment]
comecei e parei..mas podemos tocar juntos..

**Comment by mariohmol** [comment]
qual layout vc tem ? de qual banco?
