### ISSUE TITLE
Como usar essa lib?

### ISSUE THREAD

**Issue by d3roch4** [banco-br/nodejs-cnab#8]
Tem algum exemplo de uso para processar os arquivos de retorno?

**Comment by mariohmol** [comment]
Veja se isso te ajuda https://github.com/mariohmol/nodejs-cnab/blob/master/test/retorno.js

**Comment by mariohmol** [comment]
Adicionei uma documentacao  https://github.com/banco-br/nodejs-cnab#remessa
